"""压平迁移：初始 schema 至最新（squashed）。

由 24 个线性迁移按依赖链顺序原样拼接而成（各文件 upgrade/downgrade 分别
重命名为 _<rev>_up/_<rev>_down，模块级常量/helper/import 共享）。
schema 结果与顺序执行原 24 个迁移完全一致。使用 replaces 兼容旧 alembic_version
（已在其上 stamp 的库视为已到达本基线）。无行数据迁移。
"""

from __future__ import annotations
from collections.abc import Sequence
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql import text
from app.models.enums import SecurityType
from sqlalchemy import text
import logging
import uuid
from app.models.log import AppLog  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = "squashed_0001_initial"
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None
replaces: list[str] = [
    "9a787407d654",
    "b1c2d3e4f5a6",
    "c2d3e4f5a6b7",
    "d3e4f5a6b7c8",
    "e4f5a6b7c8d9",
    "f5a6b7c8d9e0",
    "g6b7c8d9e0f1",
    "h7c8d9e0f1g2",
    "i8d9e0f1g2h3",
    "j9e0f1a2b3c4",
    "k0f1a2b3c4d5",
    "l1a2b3c4d5e6",
    "n2c3d4e5f6g7",
    "o3d4e5f6a7b8",
    "p4f7a8b9c0d1",
    "q9a8b7c6d5e4",
    "r6e5f4a3b2c1d",
    "s1a2b3c4d5e6f",
    "t0u1v2w3x4y5",
    "t7u8v9w0x1y2",
    "u1v2w3x4y5z6",
    "v2w3x4y5z6a7",
    "w3x4y5z6a7b8",
    "x4y5z6a7b8c9"
]


"""initial schema (Phase 1: 12 models + 6 enums)

Revision ID: 9a787407d654
Revises: 
Create Date: 2026-08-08 11:07:12.541162
"""



# revision identifiers, used by Alembic.


def _9a787407d654_up() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('avatar', sa.String(length=512), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('bio', sa.String(length=200), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('portfolios',
    sa.Column('id', sa.String(length=36), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_date', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_portfolios_user_id', 'portfolios', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.String(length=36), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('default_portfolio_id', sa.String(length=36), nullable=True),
    sa.Column('default_granularity', sa.String(length=20), nullable=False),
    sa.Column('default_date_range', sa.String(length=20), nullable=False),
    sa.Column('aggregation', sa.String(length=20), nullable=False),
    sa.Column('week_starts_on', sa.Integer(), nullable=False),
    sa.Column('nav_decimals', sa.Integer(), nullable=False),
    sa.Column('xirr_decimals', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(length=20), nullable=False),
    sa.Column('stale_days', sa.Integer(), nullable=False),
    sa.Column('show_liquidated', sa.Boolean(), nullable=False),
    sa.Column('cost_basis_view', sa.String(length=20), nullable=False),
    sa.Column('cash_hint_on_cashflow', sa.Boolean(), nullable=False),
    sa.Column('cash_hint_on_trade', sa.Boolean(), nullable=False),
    sa.Column('amount_thousands', sa.Boolean(), nullable=False),
    sa.Column('amount_abbrev', sa.Boolean(), nullable=False),
    sa.Column('dashboard_layout', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_preferences_user_id')
    )
    op.create_table('asset_snapshots',
    sa.Column('id', sa.String(length=36), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_asset', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('market_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cash_balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('source', sa.Enum('DERIVED', 'MANUAL', name='SnapshotSource'), nullable=False),
    sa.Column('valuation_flag', sa.Enum('EXACT', 'CARRIED_FORWARD', 'COST_BASED', 'MANUAL_INPUT', name='SnapshotValuation'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'date', name='uq_asset_snapshots_portfolio_date')
    )
    op.create_index('ix_asset_snapshots_portfolio_date', 'asset_snapshots', ['portfolio_id', 'date'], unique=False)
    op.create_table('cash_balances',
    sa.Column('id', sa.String(length=36), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cash_balances_portfolio_asof', 'cash_balances', ['portfolio_id', 'as_of'], unique=False)
    op.create_table('cashflows',
    sa.Column('id', sa.String(length=36), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.Enum('BUY', 'SELL', name='CashFlowType'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cashflows_portfolio_date', 'cashflows', ['portfolio_id', 'date'], unique=False)
    op.create_table('daily_nav',
    sa.Column('id', sa.String(length=36), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('unit_nav', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('cumulative_nav', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('year_nav', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('shares', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('base_cumulative_nav', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'date', name='uq_daily_nav_portfolio_date')
    )
    op.create_index('ix_daily_nav_portfolio_date', 'daily_nav', ['portfolio_id', 'date'], unique=False)
    op.create_table('daily_xirr',
    sa.Column('id', sa.String(length=36), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('xirr_value', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'date', name='uq_daily_xirr_portfolio_date')
    )
    op.create_index('ix_daily_xirr_portfolio_date', 'daily_xirr', ['portfolio_id', 'date'], unique=False)
    op.create_table('securities',
    sa.Column('id', sa.String(length=36), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('STOCK', 'FUND', 'BOND', 'OTHER', 'CASH', name='SecurityType'), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'code', name='uq_securities_portfolio_code')
    )
    op.create_table('dividend_records',
    sa.Column('id', sa.String(length=36), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('security_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('type', sa.Enum('CASH', 'STOCK_DIVIDEND', name='DividendType'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dividend_records_portfolio_date', 'dividend_records', ['portfolio_id', 'date'], unique=False)
    op.create_index('ix_dividend_records_security_date', 'dividend_records', ['security_id', 'date'], unique=False)
    op.create_table('security_prices',
    sa.Column('id', sa.String(length=36), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('security_id', sa.String(length=36), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_security_prices_portfolio_security_asof', 'security_prices', ['portfolio_id', 'security_id', 'as_of'], unique=False)
    op.create_table('security_trades',
    sa.Column('id', sa.String(length=36), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('security_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('side', sa.Enum('BUY_SEC', 'SELL_SEC', name='SecuritySide'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('fee_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('commission', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('stamp_tax', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('other', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_security_trades_portfolio_date', 'security_trades', ['portfolio_id', 'date'], unique=False)
    op.create_index('ix_security_trades_security_date', 'security_trades', ['security_id', 'date'], unique=False)
    # ### end Alembic commands ###


def _9a787407d654_down() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_security_trades_security_date', table_name='security_trades')
    op.drop_index('ix_security_trades_portfolio_date', table_name='security_trades')
    op.drop_table('security_trades')
    op.drop_index('ix_security_prices_portfolio_security_asof', table_name='security_prices')
    op.drop_table('security_prices')
    op.drop_index('ix_dividend_records_security_date', table_name='dividend_records')
    op.drop_index('ix_dividend_records_portfolio_date', table_name='dividend_records')
    op.drop_table('dividend_records')
    op.drop_table('securities')
    op.drop_index('ix_daily_xirr_portfolio_date', table_name='daily_xirr')
    op.drop_table('daily_xirr')
    op.drop_index('ix_daily_nav_portfolio_date', table_name='daily_nav')
    op.drop_table('daily_nav')
    op.drop_index('ix_cashflows_portfolio_date', table_name='cashflows')
    op.drop_table('cashflows')
    op.drop_index('ix_cash_balances_portfolio_asof', table_name='cash_balances')
    op.drop_table('cash_balances')
    op.drop_index('ix_asset_snapshots_portfolio_date', table_name='asset_snapshots')
    op.drop_table('asset_snapshots')
    op.drop_table('user_preferences')
    op.drop_index('ix_portfolios_user_id', table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_table('users')
    # ### end Alembic commands ###


"""add users.role + system_configs table

Revision ID: b1c2d3e4f5a6
Revises: 9a787407d654
Create Date: 2026-08-11 12:00:00.000000
"""



# revision identifiers, used by Alembic.


def _b1c2d3e4f5a6_up() -> None:
    # users.role：默认 'user'，非空（存量用户回填为普通用户）
    op.add_column(
        'users',
        sa.Column(
            'role',
            sa.String(length=20),
            server_default=sa.text("'user'"),
            nullable=False,
        ),
    )
    # system_configs：键值型系统配置
    op.create_table(
        'system_configs',
        sa.Column(
            'id',
            sa.String(length=36),
            server_default=sa.text('gen_random_uuid()'),
            nullable=False,
        ),
        sa.Column('key', sa.String(length=255), nullable=False),
        sa.Column('config_value', postgresql.JSONB(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('updated_by', sa.String(length=255), nullable=True),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('key'),
    )


def _b1c2d3e4f5a6_down() -> None:
    op.drop_table('system_configs')
    op.drop_column('users', 'role')


"""add securities_data_providers; drop system_configs

取代旧的单 URL 系统配置（admin 路由的 system-config 端点），改为多提供方管理。
securities_data_providers 表结构与模型 SecuritiesDataProvider 对齐。

Revision ID: c2d3e4f5a6b7
Revises: b1c2d3e4f5a6
Create Date: 2026-08-12 12:00:00.000000
"""



# revision identifiers, used by Alembic.


def _c2d3e4f5a6b7_up() -> None:
    op.create_table(
        "securities_data_providers",
        sa.Column(
            "id",
            sa.String(length=36),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("provider_type", sa.String(length=50), nullable=False),
        sa.Column("access_method", sa.String(length=20), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("enabled", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("system_configs")


def _c2d3e4f5a6b7_down() -> None:
    op.drop_table("securities_data_providers")
    op.create_table(
        "system_configs",
        sa.Column(
            "id",
            sa.String(length=36),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("config_value", sa.JSON(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("updated_by", sa.String(length=255), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )


"""add quote_provider_interfaces + quote_provider_interface_categories

新增「提供方接口」与「接口分类」两张表，支持证券行情数据提供方下的接口 CRUD
与接口分类后台管理（系统管理扩展特性）。

- quote_provider_interfaces：provider_id 外键 → securities_data_providers.id，
  ON DELETE CASCADE（删除提供方级联删接口）；direction 用 PG 原生枚举 interface_direction。
- quote_provider_interface_categories：key 唯一约束；upgrade 末尾 INSERT 7 个预置分类。

**迁移红线**：本文件必须接在链头 c2d3e4f5a6b7 之后（down_revision='c2d3e4f5a6b7'），
严禁改动/删除 c2d3e4f5a6b7_add_quote_providers_drop_system_configs.py，否则断链。

Revision ID: d3e4f5a6b7c8
Revises: c2d3e4f5a6b7
Create Date: 2026-08-12 16:00:00.000000
"""



# revision identifiers, used by Alembic.

# 预置接口分类（key / label / icon / sort_order），icon 取合理 lucide 名。
SEED_CATEGORIES: list[tuple[str, str, str, int]] = [
    ("ashare_list", "A股列表", "List", 1),
    ("ashare_quote", "A股行情", "LineChart", 2),
    ("hk_list", "港股列表", "ListOrdered", 3),
    ("hk_quote", "港股行情", "LineChart", 4),
    ("fund_list", "基金列表", "List", 5),
    ("convertible_list", "可转债列表", "ListChecks", 6),
    ("convertible_quote", "可转债行情", "TrendingUp", 7),
]


def _d3e4f5a6b7c8_up() -> None:
    # 1) PG 原生枚举 `interface_direction` 由下方 quote_provider_interfaces 表的
    #    direction 列（sa.Enum('in','out', name='interface_direction')）在 op.create_table
    #    时自动创建一次（create_type 默认 True）。不要额外显式 CREATE TYPE，否则会重复创建报错。

    op.create_table(
        "quote_provider_interfaces",
        sa.Column(
            "id",
            sa.String(length=36),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "provider_id",
            sa.String(length=36),
            nullable=False,
            index=True,
        ),
        sa.Column("interface_type", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("endpoint", sa.String(length=512), nullable=True),
        sa.Column("http_method", sa.String(length=10), nullable=True),
        sa.Column("params", sa.JSON(), nullable=True),
        sa.Column(
            "enabled",
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "direction",
            sa.Enum("in", "out", name="interface_direction"),
            nullable=False,
            server_default="in",
        ),
        sa.Column("timeout", sa.Integer(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=True),
        sa.Column("rate_limit", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["securities_data_providers.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "quote_provider_interface_categories",
        sa.Column(
            "id",
            sa.String(length=36),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=128), nullable=False),
        sa.Column("icon", sa.String(length=64), nullable=True),
        sa.Column(
            "sort_order",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("0"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )

    # 2) 预置 7 个接口分类
    bind = op.get_bind()
    for key, label, icon, sort_order in SEED_CATEGORIES:
        bind.execute(
            sa.text(
                "INSERT INTO quote_provider_interface_categories "
                "(id, key, label, icon, sort_order, created_at, updated_at) "
                "VALUES (gen_random_uuid(), :key, :label, :icon, :sort_order, now(), now())"
            ),
            {"key": key, "label": label, "icon": icon, "sort_order": sort_order},
        )


def _d3e4f5a6b7c8_down() -> None:
    op.drop_table("quote_provider_interface_categories")
    op.drop_table("quote_provider_interfaces")
    op.execute(sa.text("DROP TYPE IF EXISTS interface_direction"))


"""drop provider_type column from securities_data_providers

移除「数据来源」的 provider_type 列：该字段仅为展示性自由文本标识，
不参与任何运行时解析（当前/默认选择只看 is_active/is_default），且前后端
语义未统一（后端 docstring 指厂商、前端占位指资产类别），故整体移除。

链：接在 d3e4f5a6b7c8 之后。

Revision ID: e4f5a6b7c8d9
Revises: d3e4f5a6b7c8
Create Date: 2026-08-13 01:30:00.000000
"""



# revision identifiers, used by Alembic.


def _e4f5a6b7c8d9_up() -> None:
    op.drop_column("securities_data_providers", "provider_type")


def _e4f5a6b7c8d9_down() -> None:
    op.add_column(
        "securities_data_providers",
        sa.Column("provider_type", sa.String(length=50), nullable=False),
    )


"""B2 + 选项 ii：接口分类改纯外键 + 移除分类 key 列

将 quote_provider_interfaces 的「分类」由自由文本 interface_type 改为外键
category_id → quote_provider_interface_categories.id（ON DELETE SET NULL），
并删除接口分类表的 key 列（含其 UNIQUE 约束）。

- upgrade：
  ① 新增 category_id 列 + 外键 + 索引；
  ② backfill：把旧 interface_type（分类 key）回填成匹配分类的 id；
     匹配不上（自定义/脏数据）→ NULL（即「未分类」）；
  ③ 删除旧 interface_type 列；
  ④ 删除分类表 key 列（其 UNIQUE 约束随列删除由 PostgreSQL 自动移除）。
- downgrade：反向重建，并把 category_id 写回 interface_type（按 id 反查 key）。

链：接在 e4f5a6b7c8d9 之后。
Revision ID: f5a6b7c8d9e0
Revises: e4f5a6b7c8d9
Create Date: 2026-08-13 03:00:00.000000
"""



# revision identifiers, used by Alembic.


def _f5a6b7c8d9e0_up() -> None:
    # ① 新增 category_id 列 + 外键 + 索引
    op.add_column(
        "quote_provider_interfaces",
        sa.Column("category_id", sa.String(length=36), nullable=True),
    )
    op.create_foreign_key(
        "fk_quote_provider_interfaces_category_id",
        "quote_provider_interfaces",
        "quote_provider_interface_categories",
        ["category_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_index(
        "ix_quote_provider_interfaces_category_id",
        "quote_provider_interfaces",
        ["category_id"],
    )

    # ② backfill：旧 interface_type（分类 key）回填成匹配分类的 id；
    # 匹配不上（自定义/脏数据）→ 保持 NULL（即「未分类」）
    op.execute(
        sa.text(
            "UPDATE quote_provider_interfaces "
            "SET category_id = ("
            "    SELECT quote_provider_interface_categories.id "
            "    FROM quote_provider_interface_categories "
            "    WHERE quote_provider_interface_categories.key = quote_provider_interfaces.interface_type"
            ") "
            "WHERE quote_provider_interfaces.interface_type IS NOT NULL"
        )
    )

    # ③ 删除旧 interface_type 列
    op.drop_column("quote_provider_interfaces", "interface_type")

    # ④ 删除分类表 key 列（UNIQUE 约束随列删除由 PostgreSQL 自动移除）
    op.drop_column("quote_provider_interface_categories", "key")


def _f5a6b7c8d9e0_down() -> None:
    # ④ 反向：重加 key 列（先可空，回填后转 NOT NULL 以满足原约束）
    op.add_column(
        "quote_provider_interface_categories",
        sa.Column("key", sa.String(length=64), nullable=True),
    )
    op.execute(
        sa.text(
            "UPDATE quote_provider_interface_categories "
            "SET key = 'cat_' || replace(id, '-', '') "
            "WHERE key IS NULL"
        )
    )
    op.alter_column("quote_provider_interface_categories", "key", nullable=False)
    op.create_unique_constraint(
        "uq_quote_provider_interface_categories_key",
        "quote_provider_interface_categories",
        ["key"],
    )

    # ③ 反向：重加 interface_type 列（先可空，回填后转 NOT NULL）
    op.add_column(
        "quote_provider_interfaces",
        sa.Column("interface_type", sa.String(length=64), nullable=True),
    )
    op.execute(
        sa.text(
            "UPDATE quote_provider_interfaces "
            "SET interface_type = COALESCE(("
            "    SELECT quote_provider_interface_categories.key "
            "    FROM quote_provider_interface_categories "
            "    WHERE quote_provider_interface_categories.id = quote_provider_interfaces.category_id"
            "), 'uncategorized')"
        )
    )
    op.alter_column("quote_provider_interfaces", "interface_type", nullable=False)

    # ① 反向：删外键 + 索引 + category_id 列
    op.drop_constraint(
        "fk_quote_provider_interfaces_category_id",
        "quote_provider_interfaces",
        type_="foreignkey",
    )
    op.drop_column("quote_provider_interfaces", "category_id")


"""market data priority chain (ADR-002 方案 X)

分类级接口优先级链 + 顺序 fallback + 连续失败告警 + 数据时效字段：

- quote_provider_interfaces：+priority / +consecutive_failures / +alerted /
  +resp_code_field / +resp_price_field
- securities_data_providers：-is_default / -is_active（全局单一活跃源完全移除，
  提供方仅保留 enabled 开关）
- security_prices：+fetched_at / +source

**迁移红线**：本文件必须接在链头 f5a6b7c8d9e0 之后（down_revision='f5a6b7c8d9e0'），
严禁改动任何既有迁移文件，否则断链。
"""



# revision identifiers, used by Alembic.


def _g6b7c8d9e0f1_up() -> None:
    # 1) quote_provider_interfaces 新增 5 列
    op.add_column(
        "quote_provider_interfaces",
        sa.Column("priority", sa.Integer(), nullable=True),
    )
    op.create_index(
        "ix_quote_provider_interfaces_priority",
        "quote_provider_interfaces",
        ["priority"],
        unique=False,
    )
    op.add_column(
        "quote_provider_interfaces",
        sa.Column(
            "consecutive_failures",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
    )
    op.add_column(
        "quote_provider_interfaces",
        sa.Column(
            "alerted",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.add_column(
        "quote_provider_interfaces",
        sa.Column(
            "resp_code_field",
            sa.String(length=64),
            nullable=False,
            server_default="code",
        ),
    )
    op.add_column(
        "quote_provider_interfaces",
        sa.Column(
            "resp_price_field",
            sa.String(length=64),
            nullable=False,
            server_default="price",
        ),
    )

    # 2) securities_data_providers 移除全局活跃源两列
    op.drop_column("securities_data_providers", "is_default")
    op.drop_column("securities_data_providers", "is_active")

    # 3) security_prices 新增数据时效字段
    op.add_column(
        "security_prices",
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "security_prices",
        sa.Column("source", sa.String(length=64), nullable=True),
    )


def _g6b7c8d9e0f1_down() -> None:
    op.drop_column("security_prices", "source")
    op.drop_column("security_prices", "fetched_at")

    op.add_column(
        "securities_data_providers",
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.add_column(
        "securities_data_providers",
        sa.Column(
            "is_default",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )

    op.drop_column("quote_provider_interfaces", "resp_price_field")
    op.drop_column("quote_provider_interfaces", "resp_code_field")
    op.drop_column("quote_provider_interfaces", "alerted")
    op.drop_column("quote_provider_interfaces", "consecutive_failures")
    op.drop_index(
        "ix_quote_provider_interfaces_priority",
        table_name="quote_provider_interfaces",
    )
    op.drop_column("quote_provider_interfaces", "priority")


"""add notifications table (ADR-002 §3 Q2 站内信告警落点)

新增 notifications 表，承接 ``MarketDataSyncService._mark_failure`` 抢占成功后的告警写入。

**迁移红线**：本文件必须接在 g6b7c8d9e0f1（market data priority chain）之后
（down_revision='g6b7c8d9e0f1'），严禁改动任何既有迁移文件，否则断链。
"""



# revision identifiers, used by Alembic.


def _h7c8d9e0f1g2_up() -> None:
    op.create_table(
        "notifications",
        sa.Column(
            "id",
            sa.String(length=36),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "level", sa.String(length=20), nullable=False, server_default="warning"
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("related_type", sa.String(length=40), nullable=True),
        sa.Column("related_id", sa.String(length=36), nullable=True),
        sa.Column("read", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )


def _h7c8d9e0f1g2_down() -> None:
    op.drop_table("notifications")


"""securities master data + quote interface master_list purpose (股票列表和测试).

Revises: h7c8d9e0f1g2
- SecurityType 原生枚举扩展 HK_STOCK / CONVERTIBLE_BOND / ETF / INDEX
  （ALTER TYPE ADD VALUE 不能在事务块内执行，故用 autocommit_block 单独执行）。
- securities：portfolio_id 改可空 + 新增 exchange / pinyin_initials / asset_class
  + 部分唯一索引 uq_securities_master_asset_code(asset_class, code) WHERE portfolio_id IS NULL
  + ix_securities_pinyin_initials 索引。
- quote_provider_interfaces：新增 purpose / asset_class / resp_name_field / resp_exchange_field。

Create Date: 2026-08-13
"""


# revision identifiers, used by Alembic.

# SecurityType 既有值之外的扩展值（§11.3）
NEW_SECURITY_TYPES = ("HK_STOCK", "CONVERTIBLE_BOND", "ETF", "INDEX")


def _i8d9e0f1g2h3_up() -> None:
    # 1) 扩展 SecurityType 原生枚举。PG 要求 ALTER TYPE ADD VALUE 不能在事务块内执行，
    #    autocommit_block 将其隔离在独立 autocommit 连接上执行。
    ctx = op.get_context()
    with ctx.autocommit_block():
        for v in NEW_SECURITY_TYPES:
            op.execute(
                text(f"ALTER TYPE \"SecurityType\" ADD VALUE IF NOT EXISTS '{v}'")
            )

    # 2) securities：portfolio_id 可空 + 主数据字段
    # 新建原生枚举 InterfacePurpose（CREATE TYPE 允许在事务内执行；DO 块保证幂等）
    op.execute(
        text(
            "DO $$ BEGIN "
            "IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname='interfacepurpose') "
            "THEN CREATE TYPE \"InterfacePurpose\" AS ENUM ('QUOTE','MASTER_LIST'); "
            "END IF; END $$"
        )
    )
    op.alter_column(
        "securities",
        "portfolio_id",
        existing_type=sa.String(length=36),
        nullable=True,
        existing_nullable=False,
    )
    op.add_column(
        "securities",
        sa.Column("exchange", sa.String(length=10), nullable=True),
    )
    op.add_column(
        "securities",
        sa.Column("pinyin_initials", sa.String(length=64), nullable=True),
    )
    op.add_column(
        "securities",
        sa.Column(
            "asset_class",
            # 复用既有 SecurityType 原生枚举（create_type=False 不重复建类型）
            postgresql.ENUM(
                "STOCK", "FUND", "BOND", "OTHER", "CASH",
                "HK_STOCK", "CONVERTIBLE_BOND", "ETF", "INDEX",
                name="SecurityType", create_type=False,
            ),
            nullable=True,
        ),
    )
    # 系统级主数据行（portfolio_id IS NULL）按 资产类别+code 唯一（部分唯一索引）
    op.create_index(
        "uq_securities_master_asset_code",
        "securities",
        ["asset_class", "code"],
        unique=True,
        postgresql_where=text("portfolio_id IS NULL"),
    )
    op.create_index(
        "ix_securities_pinyin_initials", "securities", ["pinyin_initials"], unique=False
    )

    # 3) quote_provider_interfaces：列表接口配置字段
    op.add_column(
        "quote_provider_interfaces",
        sa.Column(
            "purpose",
            # 新建原生枚举 InterfacePurpose（已在上方 DO 块创建，create_type=False 不重复建）
            postgresql.ENUM("QUOTE", "MASTER_LIST", name="InterfacePurpose", create_type=False),
            nullable=False,
            server_default="QUOTE",
        ),
    )
    op.add_column(
        "quote_provider_interfaces",
        sa.Column(
            "asset_class",
            postgresql.ENUM(
                "STOCK", "FUND", "BOND", "OTHER", "CASH",
                "HK_STOCK", "CONVERTIBLE_BOND", "ETF", "INDEX",
                name="SecurityType", create_type=False,
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "quote_provider_interfaces",
        sa.Column(
            "resp_name_field",
            sa.String(length=64),
            nullable=True,
            server_default="name",
        ),
    )
    op.add_column(
        "quote_provider_interfaces",
        sa.Column("resp_exchange_field", sa.String(length=64), nullable=True),
    )


def _i8d9e0f1g2h3_down() -> None:
    op.drop_index("ix_securities_pinyin_initials", table_name="securities")
    op.drop_index("uq_securities_master_asset_code", table_name="securities")
    op.drop_column("quote_provider_interfaces", "resp_exchange_field")
    op.drop_column("quote_provider_interfaces", "resp_name_field")
    op.drop_column("quote_provider_interfaces", "asset_class")
    op.drop_column("quote_provider_interfaces", "purpose")
    op.drop_column("securities", "asset_class")
    op.drop_column("securities", "pinyin_initials")
    op.drop_column("securities", "exchange")
    op.alter_column(
        "securities",
        "portfolio_id",
        existing_type=sa.String(length=36),
        nullable=False,
        existing_nullable=True,
    )
    # PG 不支持 DROP VALUE，故不再回退 SecurityType 枚举值；
    # InterfacePurpose 类型在此保留（无害，且不影响既有表）。


"""SecurityType 枚举调整：新增 LOF、停用 CASH (资产类型体系收窄).

Revises: i8d9e0f1g2h3
- ALTER TYPE SecurityType ADD VALUE 'LOF'（PG 要求 ADD VALUE 在事务块外，用 autocommit_block）。
- CASH 枚举值**保留在数据库**：asyncpg 扩展查询协议不支持 `ALTER TYPE ... DROP VALUE`
  （PG 16 实测语法错误），故无法在迁移中删除枚举值；代码层面已移除 CASH，
  不再产生/读取该值，历史遗留的 CASH 值不影响功能。

Create Date: 2026-08-14
"""


# revision identifiers, used by Alembic.


def _j9e0f1a2b3c4_up() -> None:
    # ADD VALUE 不能在事务块内执行，用 autocommit_block 隔离执行
    ctx = op.get_context()
    with ctx.autocommit_block():
        op.execute(text("ALTER TYPE \"SecurityType\" ADD VALUE IF NOT EXISTS 'LOF'"))


def _j9e0f1a2b3c4_down() -> None:
    # 回退：无法删除已 ADD 的 LOF（asyncpg 不支持 DROP VALUE），且需先转换数据；
    # 此处保留 LOF 值（无害），仅记录说明。
    pass


"""证券数据模型拆表：目录表 securities + 组合持仓表 portfolio_securities（ADR-003）。

D1 已决「干净重建」：本迁移仅含 schema 操作，不迁移任何存量数据。
- securities 去 portfolio_id / type / currency 列；唯一约束收敛为 (asset_class, code)。
- 新增 portfolio_securities（组合持仓表），承载 trades/prices/dividends。
- SecurityTrade/SecurityPrice/DividendRecord.security_id 外键目标由 securities.id
  改为 portfolio_securities.id（ondelete=CASCADE 不变）。

应用方式（D1）：因涉及外键目标切换与列删除，建议在「整库重建」后跑 alembic upgrade head
（开发库先 pg_dump，再 DROP+CREATE 后 upgrade head；测试库由 conftest 每会话自动重建），
而非对含数据的旧库做增量升级。SecurityType 原生枚举沿用既有类型（create_type=False），
由本迁移之前的 securities.type 列创建，删除该列不删除枚举类型。
"""



# revision identifiers, used by Alembic.


def _k0f1a2b3c4d5_up() -> None:
    # 1) securities：先删旧约束/索引，再删列，最后加新唯一约束
    op.drop_constraint("uq_securities_portfolio_code", "securities", type_="unique")
    op.drop_index("uq_securities_master_asset_code", table_name="securities")
    op.drop_column("securities", "portfolio_id")
    op.drop_column("securities", "type")
    op.drop_column("securities", "currency")
    op.create_unique_constraint(
        "uq_securities_asset_code", "securities", ["asset_class", "code"]
    )

    # 2) 三张子表外键目标：securities.id → portfolio_securities.id
    op.drop_constraint("security_trades_security_id_fkey", "security_trades", type_="foreignkey")
    op.drop_constraint("security_prices_security_id_fkey", "security_prices", type_="foreignkey")
    op.drop_constraint("dividend_records_security_id_fkey", "dividend_records", type_="foreignkey")

    # 3) 新建组合持仓表
    op.create_table(
        "portfolio_securities",
        sa.Column(
            "id",
            sa.String(36),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "portfolio_id",
            sa.String(36),
            sa.ForeignKey("portfolios.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "master_id",
            sa.String(36),
            sa.ForeignKey("securities.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "type",
            postgresql.ENUM(
                SecurityType,
                name="SecurityType",
                create_type=False,
            ),
            nullable=True,
        ),
        sa.Column("currency", sa.String(10), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.UniqueConstraint(
            "portfolio_id",
            "master_id",
            name="uq_portfolio_securities_portfolio_master",
        ),
    )
    op.create_index(
        "ix_portfolio_securities_portfolio", "portfolio_securities", ["portfolio_id"]
    )

    # 4) 子表外键指向新表
    op.create_foreign_key(
        "security_trades_security_id_fkey",
        "security_trades",
        "portfolio_securities",
        ["security_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "security_prices_security_id_fkey",
        "security_prices",
        "portfolio_securities",
        ["security_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "dividend_records_security_id_fkey",
        "dividend_records",
        "portfolio_securities",
        ["security_id"],
        ["id"],
        ondelete="CASCADE",
    )


def _k0f1a2b3c4d5_down() -> None:
    # 1) 子表外键指回 securities.id
    op.drop_constraint("security_trades_security_id_fkey", "security_trades", type_="foreignkey")
    op.drop_constraint("security_prices_security_id_fkey", "security_prices", type_="foreignkey")
    op.drop_constraint("dividend_records_security_id_fkey", "dividend_records", type_="foreignkey")
    op.create_foreign_key(
        "security_trades_security_id_fkey",
        "security_trades",
        "securities",
        ["security_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "security_prices_security_id_fkey",
        "security_prices",
        "securities",
        ["security_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "dividend_records_security_id_fkey",
        "dividend_records",
        "securities",
        ["security_id"],
        ["id"],
        ondelete="CASCADE",
    )

    # 2) 删组合持仓表
    op.drop_index("ix_portfolio_securities_portfolio", table_name="portfolio_securities")
    op.drop_table("portfolio_securities")

    # 3) securities 复原列与旧约束
    op.drop_constraint("uq_securities_asset_code", "securities", type_="unique")
    op.add_column(
        "securities",
        sa.Column(
            "portfolio_id",
            sa.String(36),
            sa.ForeignKey("portfolios.id", ondelete="CASCADE"),
            nullable=True,
        ),
    )
    op.add_column(
        "securities",
        sa.Column(
            "type",
            postgresql.ENUM(
                SecurityType,
                name="SecurityType",
                create_type=False,
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "securities",
        sa.Column("currency", sa.String(10), nullable=False, server_default="CNY"),
    )
    op.create_unique_constraint(
        "uq_securities_portfolio_code", "securities", ["portfolio_id", "code"]
    )
    op.create_index(
        "uq_securities_master_asset_code",
        "securities",
        ["asset_class", "code"],
        unique=True,
        postgresql_where=sa.text("portfolio_id IS NULL"),
    )


"""add response_parse to quote_provider_interfaces

为接口表新增 `response_parse` JSON 列，承载接口级响应解析协议
{format, encoding, sep, line_regex, code_param}，用于接入腾讯财经等
非 JSON 文本源（gbk 编码 + ~ 分隔）。可空、默认 {}，向后兼容，无需重建表。

**迁移红线**：本文件必须接在链头 k0f1a2b3c4d5 之后（down_revision='k0f1a2b3c4d5'）。

Revision ID: l1a2b3c4d5e6
Revises: k0f1a2b3c4d5
Create Date: 2026-08-15 16:00:00.000000
"""



# revision identifiers, used by Alembic.


def _l1a2b3c4d5e6_up() -> None:
    op.add_column(
        "quote_provider_interfaces",
        sa.Column("response_parse", sa.JSON(), nullable=True),
    )


def _l1a2b3c4d5e6_down() -> None:
    op.drop_column("quote_provider_interfaces", "response_parse")


"""SecurityType 枚举调整：FUND→ON_EXCHANGE_FUND（场内基金），新增 OFF_EXCHANGE_FUND（场外基金），ETF/LOF 合并入场内基金。

- ALTER TYPE RENAME VALUE 'FUND' TO 'ON_EXCHANGE_FUND'：既有 FUND 行随枚举值更名自动继承（无需数据迁移）。
- ALTER TYPE ADD VALUE 'OFF_EXCHANGE_FUND'。
- ETF/LOF 物理值 PG 不支持 DROP（见 j9e0f1a2b3c4），故仅从 Python 枚举 / UI / 用法中移除；
  升级前先把任何残留 ETF/LOF 行归并到 ON_EXCHANGE_FUND，避免 Python 枚举缺成员导致加载失败。
"""


# revision identifiers, used by Alembic.


def _n2c3d4e5f6g7_up() -> None:
    ctx = op.get_context()
    with ctx.autocommit_block():
        # FUND 重命名为场内基金（保留数据）
        op.execute(
            text('ALTER TYPE "SecurityType" RENAME VALUE \'FUND\' TO \'ON_EXCHANGE_FUND\'')
        )
        # 新增场外基金
        op.execute(
            text("ALTER TYPE \"SecurityType\" ADD VALUE IF NOT EXISTS 'OFF_EXCHANGE_FUND'")
        )
    # 残留 ETF/LOF 行归并到场内基金（PG 不支持 DROP VALUE，物理值保留但不再使用）
    op.execute(
        text(
            "UPDATE securities SET asset_class='ON_EXCHANGE_FUND' "
            "WHERE asset_class IN ('ETF','LOF')"
        )
    )
    op.execute(
        text(
            "UPDATE portfolio_securities SET type='ON_EXCHANGE_FUND' "
            "WHERE type IN ('ETF','LOF')"
        )
    )
    op.execute(
        text(
            "UPDATE quote_provider_interfaces SET asset_class='ON_EXCHANGE_FUND' "
            "WHERE asset_class IN ('ETF','LOF')"
        )
    )


def _n2c3d4e5f6g7_down() -> None:
    # 物理值 OFF_EXCHANGE_FUND 无法 DROP（PG 限制），仅逆转换数据并恢复 FUND 名。
    # 已合并的 ETF/LOF 行无法还原原始子类型（升级时信息已丢失），统一回退为场内基金。
    ctx = op.get_context()
    with ctx.autocommit_block():
        op.execute(
            text('ALTER TYPE "SecurityType" RENAME VALUE \'ON_EXCHANGE_FUND\' TO \'FUND\'')
        )
    op.execute(
        text(
            "UPDATE securities SET asset_class='FUND' "
            "WHERE asset_class='ON_EXCHANGE_FUND'"
        )
    )
    op.execute(
        text(
            "UPDATE portfolio_securities SET type='FUND' "
            "WHERE type='ON_EXCHANGE_FUND'"
        )
    )
    op.execute(
        text(
            "UPDATE quote_provider_interfaces SET asset_class='FUND' "
            "WHERE asset_class='ON_EXCHANGE_FUND'"
        )
    )


"""接口分类改版：固定 2 类 + 废弃 InterfacePurpose

按 plan-interface-category-reform-2026-08-15 落地（用户明确"无需考虑存量数据"）：
1. 接口分类表新增 system 列（Boolean，default false）——标识系统内置分类。
2. 清空旧 7 个预置分类（接口 category_id 因 FK ON DELETE SET NULL 自动置空）。
3. INSERT 2 个固定 system 分类（显式固定 id，便于代码硬编码路由，不受重建影响）：
   - 1 证券列表（主数据拉取）
   - 2 证券行情（价格行情）
   与 backend/app/services/market_data_sync.py 的 MASTER_LIST_CAT_ID / QUOTE_CAT_ID 常量一致。
4. 删除 quote_provider_interfaces.purpose 列。
5. DROP TYPE "InterfacePurpose"（PG 原生枚举类型清理）。

注：种子迁移 d3e4f5a6b7c8 曾向 key 列 INSERT，但 key 列在后续 f5a6b7c8d9e0 已正常删除，
迁移链顺序执行后 schema 与模型一致，新鲜库不会报错，故本迁移不处理 key 列。

幂等 / 漂移容忍：本迁移所有 DDL 均带 IF [NOT] EXISTS 守卫，且分类表缺失时自动 CREATE
（建表 DDL 对齐 f5 之后无 key 列的真实结构）。这样无论是「全新迁移」还是开发库以
create_all + stamp 建库导致的漂移（漏建分类表 / 已无 purpose 列 / 已无 InterfacePurpose
枚举），一条 `alembic upgrade head` 都能收敛到同一终态，避免半程中断。
"""


# revision identifiers, used by Alembic.

# 固定分类 id（与 market_data_sync.MASTER_LIST_CAT_ID / QUOTE_CAT_ID 保持一致）
MASTER_LIST_CAT_ID = "1"
QUOTE_CAT_ID = "2"


def _o3d4e5f6a7b8_up() -> None:
    # 1) 确保分类表存在（容忍开发库以 create_all+stamp 建库、漏建本表的漂移）：
    #    建表 DDL 对齐 f5 之后（已删 key 列）的真实结构，避免与全新迁移路径产生 schema 漂移。
    op.execute(
        text(
            "CREATE TABLE IF NOT EXISTS quote_provider_interface_categories ("
            "  id VARCHAR(36) PRIMARY KEY DEFAULT gen_random_uuid(),"
            "  label VARCHAR(128) NOT NULL,"
            "  icon VARCHAR(64),"
            "  sort_order INTEGER NOT NULL DEFAULT 0,"
            "  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),"
            "  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()"
            ")"
        )
    )

    # 2) 新增 system 列（IF NOT EXISTS，可重复执行）
    op.execute(
        text(
            "ALTER TABLE quote_provider_interface_categories "
            "ADD COLUMN IF NOT EXISTS system BOOLEAN NOT NULL DEFAULT false"
        )
    )

    # 3) 清空旧分类（无存量数据，跳过旧类归并）；接口 category_id 自动置空
    op.execute(text("DELETE FROM quote_provider_interface_categories"))

    # 4) 插入 2 个固定 system 分类
    #    注：op.execute() 只接受单个 SQL 表达式，参数须用 text().bindparams() 绑定，
    #    不能像 Connection.execute() 那样传第二个 params 位置参数。
    op.execute(
        text(
            "INSERT INTO quote_provider_interface_categories "
            "(id, label, icon, sort_order, system, created_at, updated_at) "
            "VALUES "
            "(:ml_id, '证券列表', 'List', 1, TRUE, now(), now()), "
            "(:q_id, '证券行情', 'LineChart', 2, TRUE, now(), now())"
        ).bindparams(ml_id=MASTER_LIST_CAT_ID, q_id=QUOTE_CAT_ID)
    )

    # 5) 删除接口表 purpose 列（IF EXISTS，容忍已无该列的漂移库）
    op.execute(
        text("ALTER TABLE quote_provider_interfaces DROP COLUMN IF EXISTS purpose")
    )

    # 6) 清理 PG 原生枚举类型 InterfacePurpose（IF EXISTS）
    op.execute(text('DROP TYPE IF EXISTS "InterfacePurpose"'))


def _o3d4e5f6a7b8_down() -> None:
    # 5) 重建枚举类型
    op.execute(
        text(
            "CREATE TYPE \"InterfacePurpose\" AS ENUM ('QUOTE', 'MASTER_LIST')"
        )
    )
    # 4) 恢复 purpose 列（枚举类型上一步已显式 CREATE，故 create_type=False 防重复创建）
    op.add_column(
        "quote_provider_interfaces",
        sa.Column(
            "purpose",
            postgresql.ENUM(
                "QUOTE", "MASTER_LIST", name="InterfacePurpose", create_type=False
            ),
            nullable=False,
            server_default="QUOTE",
        ),
    )
    # 3) 删除固定分类
    op.execute(
        text(
            "DELETE FROM quote_provider_interface_categories "
            "WHERE id IN (:ml_id, :q_id)"
        ).bindparams(ml_id=MASTER_LIST_CAT_ID, q_id=QUOTE_CAT_ID)
    )
    # 2) 移除 system 列
    op.drop_column("quote_provider_interface_categories", "system")


"""资产类别多选 + 未分类兜底（ADR/接口分类改版后续）

背景：接口 asset_class 由「单行强制打标」改为「仅用于同步选源批次归属」的多选字段；
主数据行级 asset_class 改为逐行由代码前缀 + 交易所推断（与组合持仓 type 同源），
无法可靠区分的类（如场外基金与 A股 同前缀）落 UNCATEGORIZED 未分类。

迁移内容：
1. SecurityType 原生枚举新增 'UNCATEGORIZED' 值（PG12+ 允许事务内 ADD VALUE，
   本迁移不使用该值，仅枚举定义扩展，无事务冲突）。
2. quote_provider_interfaces.asset_class：标量原生枚举 → text[]（多选，
   存 SecurityType 值字符串），已有标量值经 ARRAY[asset_class::text] 升级为单元素数组。
"""


# revision identifiers, used by Alembic.


def _p4f7a8b9c0d1_up() -> None:
    # 1) 新增未分类枚举值（仅扩展定义，本事务不使用，PG16 事务内合法）
    #    枚举类型名带大写，必须加引号（"SecurityType"）。
    op.execute(text('ALTER TYPE "SecurityType" ADD VALUE IF NOT EXISTS \'UNCATEGORIZED\''))
    # 2) 接口 asset_class 改为多选数组（存枚举值字符串）
    op.alter_column(
        "quote_provider_interfaces",
        "asset_class",
        type_=postgresql.ARRAY(sa.String(20)),
        postgresql_using="ARRAY[asset_class::text]",
        existing_nullable=True,
    )


def _p4f7a8b9c0d1_down() -> None:
    # 回退：数组塌缩回标量（取首个元素）。未分类枚举值 PG16 不可事务内移除，略过。
    op.alter_column(
        "quote_provider_interfaces",
        "asset_class",
        type_=postgresql.ARRAY(sa.String(20)),
        postgresql_using="asset_class[1]",
        existing_nullable=True,
    )


"""证券主数据 id 由业务自然键 (asset_class, code) 确定性派生。

背景：原先 securities.id 由 DB 端 gen_random_uuid() 随机生成；证券被删除后重新同步
会得到全新 id，导致 portfolio_securities.master_id 外键引用无法稳定复用（删除即失联）。
本迁移一次性把存量 securities.id 重写为
``uuid5(固定命名空间, f"{asset_class.value}|{code}")``，
与 ``app.services.market_data_sync.master_id_for`` 完全一致，使删除重建保持同一 id。

步骤（均在 Alembic 事务内，env.py 已 ``context.begin_transaction()``）：
1. 冲突合并：重复 ``(asset_class, code)`` 组保留 ``updated_at`` 最新行，其余 dup 的持仓
   引用安全转移/删除后删除 dup 行（不级联误删）。
2. 建临时备份表 ``_sec_id_backup(old_id, new_id)`` 记录 old→new 映射（供 downgrade 还原）。
3. Python 端按 uuid5 计算新 id（SQL 无 uuid5 内置），写入备份表。
4. DROP 子表→主表 FK（动态读约束名，不硬编码）。
5. 改子表 ``portfolio_securities.master_id`` 指向新 id。
6. 改主表 ``securities.id`` 为新 id。
7. 重加 FK（ondelete=CASCADE）。
8. 校验：无孤儿、全部 id==master_id_for、前后行数一致。

注意：仅 ``UPDATE id``，**绝不 DELETE 任何 securities 行** → ondelete=CASCADE 永不触发，
绝不级联误删。换 id 期间子表外键值暂指向不存在父 id 的风险由 step4 DROP / step7 ADD 解决。
"""




# 与 app.services.market_data_sync.SECURITY_MASTER_NAMESPACE 完全一致（锁死不可改）
SECURITY_MASTER_NAMESPACE = uuid.UUID("b3f7e0c2-1a4d-4e9b-9c2a-000000000001")

log = logging.getLogger("alembic.runtime.migration")

# revision identifiers, used by Alembic.


def _master_id_for(asset_class: "SecurityType | None", code: str) -> str:
    """与 app.services.market_data_sync.master_id_for 保持一致（锁死命名空间）。"""
    ac = asset_class.value if asset_class is not None else "NULL"  # 哨兵
    return str(uuid.uuid5(SECURITY_MASTER_NAMESPACE, f"{ac}|{code}"))


def _parse_asset_class(raw: object) -> "SecurityType | None":
    """DB 原生枚举列按 text 取出时为字符串标签（如 'STOCK'），转回 SecurityType。"""
    if raw is None:
        return None
    if isinstance(raw, SecurityType):
        return raw
    return SecurityType(str(raw))


def _q9a8b7c6d5e4_up() -> None:
    bind = op.get_bind()

    # -------- step 1: 冲突合并（重复 (asset_class, code)） --------
    dup_groups = bind.execute(
        text(
            "SELECT asset_class, code, count(*) AS c "
            "FROM securities GROUP BY asset_class, code HAVING count(*) > 1"
        )
    ).fetchall()
    for ac_raw, code, _ in dup_groups:
        ac_param = None if ac_raw is None else str(ac_raw)
        rows = bind.execute(
            text(
                "SELECT id, updated_at FROM securities "
                "WHERE asset_class::text IS NOT DISTINCT FROM :ac AND code = :code "
                "ORDER BY updated_at DESC NULLS LAST, id"
            ),
            {"ac": ac_param, "code": code},
        ).fetchall()
        if len(rows) <= 1:
            continue
        keep_id = rows[0][0]
        dup_ids = [r[0] for r in rows[1:]]
        for dup_id in dup_ids:
            # 转移/清理引用该 dup 的持仓：keep 已持有→删除重复引用，否则改指 keep
            holdings = bind.execute(
                text(
                    "SELECT id, portfolio_id FROM portfolio_securities "
                    "WHERE master_id = :dup"
                ),
                {"dup": dup_id},
            ).fetchall()
            for hid, pid in holdings:
                exists = bind.execute(
                    text(
                        "SELECT 1 FROM portfolio_securities "
                        "WHERE portfolio_id = :pid AND master_id = :keep"
                    ),
                    {"pid": pid, "keep": keep_id},
                ).first()
                if exists:
                    bind.execute(
                        text("DELETE FROM portfolio_securities WHERE id = :hid"),
                        {"hid": hid},
                    )
                else:
                    bind.execute(
                        text(
                            "UPDATE portfolio_securities SET master_id = :keep "
                            "WHERE id = :hid"
                        ),
                        {"hid": hid, "keep": keep_id},
                    )
            bind.execute(
                text("DELETE FROM securities WHERE id = :dup"), {"dup": dup_id}
            )

    # -------- step 2: 备份映射表 --------
    bind.execute(
        text(
            "CREATE TABLE _sec_id_backup ("
            "old_id VARCHAR(36) PRIMARY KEY, new_id VARCHAR(36) NOT NULL)"
        )
    )

    # -------- step 3: Python 算新 id 并写入备份 --------
    sec_rows = bind.execute(
        text("SELECT id, asset_class, code FROM securities")
    ).fetchall()
    mapping: dict[str, str] = {}
    for old_id, ac_raw, code in sec_rows:
        mapping[old_id] = _master_id_for(_parse_asset_class(ac_raw), code)
    if mapping:
        bind.execute(
            text("INSERT INTO _sec_id_backup (old_id, new_id) VALUES (:old, :new)"),
            [{"old": o, "new": n} for o, n in mapping.items()],
        )

    # -------- step 4: DROP FK（动态读约束名，不硬编码） --------
    fk_name = bind.execute(
        text(
            "SELECT conname FROM pg_constraint "
            "WHERE conrelid='portfolio_securities'::regclass "
            "AND confrelid='securities'::regclass AND contype='f'"
        )
    ).scalar()
    if fk_name:
        op.drop_constraint(fk_name, "portfolio_securities", type_="foreignkey")

    # -------- step 5/6: 改子表与主表 id（经备份表 JOIN 一次性更新） --------
    bind.execute(
        text(
            "UPDATE portfolio_securities ps SET master_id = b.new_id "
            "FROM _sec_id_backup b WHERE ps.master_id = b.old_id"
        )
    )
    bind.execute(
        text(
            "UPDATE securities s SET id = b.new_id "
            "FROM _sec_id_backup b WHERE s.id = b.old_id"
        )
    )

    # -------- step 7: 重加 FK --------
    op.create_foreign_key(
        "portfolio_securities_master_id_fkey",
        "portfolio_securities",
        "securities",
        ["master_id"],
        ["id"],
        ondelete="CASCADE",
    )

    # -------- step 8: 校验（仅 log） --------
    orphan = bind.execute(
        text(
            "SELECT count(*) FROM portfolio_securities ps "
            "LEFT JOIN securities s ON ps.master_id = s.id "
            "WHERE s.id IS NULL"
        )
    ).scalar()
    bad = 0
    for old_id, ac_raw, code in sec_rows:
        new_id = mapping.get(old_id)
        if new_id is None:
            bad += 1
            continue
        if new_id != _master_id_for(_parse_asset_class(ac_raw), code):
            bad += 1
    log.info(
        "[deterministic_id] securities rows=%s, id_mismatch=%s, orphans=%s",
        len(sec_rows),
        bad,
        orphan,
    )


def _q9a8b7c6d5e4_down() -> None:
    bind = op.get_bind()

    # 动态读当前 FK 名并 DROP
    fk_name = bind.execute(
        text(
            "SELECT conname FROM pg_constraint "
            "WHERE conrelid='portfolio_securities'::regclass "
            "AND confrelid='securities'::regclass AND contype='f'"
        )
    ).scalar()
    if fk_name:
        op.drop_constraint(fk_name, "portfolio_securities", type_="foreignkey")

    # 用备份把 id 精确还原为 old_id（new_id 现作为 securities.id 存在）
    bind.execute(
        text(
            "UPDATE portfolio_securities ps SET master_id = b.old_id "
            "FROM _sec_id_backup b WHERE ps.master_id = b.new_id"
        )
    )
    bind.execute(
        text(
            "UPDATE securities s SET id = b.old_id "
            "FROM _sec_id_backup b WHERE s.id = b.new_id"
        )
    )

    op.create_foreign_key(
        "portfolio_securities_master_id_fkey",
        "portfolio_securities",
        "securities",
        ["master_id"],
        ["id"],
        ondelete="CASCADE",
    )

    bind.execute(text("DROP TABLE _sec_id_backup"))


"""统一定时任务调度：新建任务配置表 job_configs + 执行日志表 job_run_logs 与 4 个枚举。

背景：把两种既有定任务实现收敛为数据库驱动的 APScheduler AsyncIOScheduler：
- 行情同步（原 config.QUOTE_SYNC_SCHEDULER_ENABLED + scheduler.py BackgroundScheduler）
  → 迁为普通任务 MARKET_DATA_SYNC（默认关闭，沿用旧默认 cron `0 16 * * 1-5`）。
- 账户清理（原 external cron 调 /api/internal/cleanup/accounts）
  → 迁为系统任务 ACCOUNT_CLEANUP（kind=SYSTEM，默认开启，cron `0 4 * * *` 每日 04:00，
    对齐原 app @Cron(EVERY_DAY_AT_4AM) 建议频率）。
- 证券主数据同步 SECURITY_MASTER_SYNC 作为普通任务示例（默认关闭）。

任务归类权限：kind=SYSTEM 系统任务仅可编辑不可删除；kind=NORMAL 普通任务可增删改。
"""

# 列内枚举用 postgresql.ENUM(create_type=False)：由上方显式 CREATE 建枚举，
# 建表时不再重复 CREATE TYPE（sa.Enum 不接收 create_type，此处必须用 PG 专属 ENUM）

# revision identifiers, used by Alembic.


_JOB_TASK_TYPE_VALUES = [
    "MARKET_DATA_SYNC",
    "SECURITY_MASTER_SYNC",
    "LOCAL_COMMAND",
    "HTTP_CALLBACK",
    "ACCOUNT_CLEANUP",
]
_JOB_KIND_VALUES = ["SYSTEM", "NORMAL"]
_JOB_RUN_STATUS_VALUES = ["RUNNING", "SUCCESS", "FAILED"]
_JOB_TRIGGER_SOURCE_VALUES = ["SCHEDULED", "MANUAL"]


def _seed_job(
    name: str,
    task_type: str,
    kind: str,
    enabled: bool,
    cron_expr: str,
    description: str,
) -> None:
    """按 name 幂等插入任务（已存在同名校验由唯一约束兜底，勿重复执行）。"""
    # task_type/kind 为原生枚举列：asyncpg 预编译对裸参数采用 VARCHAR 类型，
    # 插入枚举列会报类型不匹配，故对这两个参数显式 cast 到目标枚举类型。
    op.execute(
        sa.text(
            "INSERT INTO job_configs "
            "(name, task_type, kind, enabled, cron_expr, params, description) "
            "SELECT :name, CAST(:task_type AS \"JobTaskType\"), "
            "CAST(:kind AS \"JobKind\"), :enabled, :cron_expr, NULL, :description "
            "WHERE NOT EXISTS (SELECT 1 FROM job_configs WHERE name = :name)"
        ).bindparams(
            name=name,
            task_type=task_type,
            kind=kind,
            enabled=enabled,
            cron_expr=cron_expr,
            description=description,
        )
    )


def _r6e5f4a3b2c1d_up() -> None:
    bind = op.get_bind()

    # 建 4 个原生 PG 枚举（checkfirst 幂等）
    sa.Enum(*_JOB_TASK_TYPE_VALUES, name="JobTaskType").create(bind, checkfirst=True)
    sa.Enum(*_JOB_KIND_VALUES, name="JobKind").create(bind, checkfirst=True)
    sa.Enum(*_JOB_RUN_STATUS_VALUES, name="JobRunStatus").create(bind, checkfirst=True)
    sa.Enum(*_JOB_TRIGGER_SOURCE_VALUES, name="JobTriggerSource").create(
        bind, checkfirst=True
    )

    # 任务配置表
    op.create_table(
        "job_configs",
        sa.Column("id", sa.String(length=36), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("task_type", postgresql.ENUM(*_JOB_TASK_TYPE_VALUES, name="JobTaskType", create_type=False), nullable=False),
        sa.Column("kind", postgresql.ENUM(*_JOB_KIND_VALUES, name="JobKind", create_type=False), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("cron_expr", sa.String(length=64), nullable=False),
        sa.Column("params", sa.JSON(), nullable=True),
        sa.Column("description", sa.String(length=512), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.UniqueConstraint("name"),
    )

    # 执行日志表
    op.create_table(
        "job_run_logs",
        sa.Column("id", sa.String(length=36), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column(
            "job_id",
            sa.String(length=36),
            sa.ForeignKey("job_configs.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("status", postgresql.ENUM(*_JOB_RUN_STATUS_VALUES, name="JobRunStatus", create_type=False), nullable=False),
        sa.Column(
            "trigger_source",
            postgresql.ENUM(*_JOB_TRIGGER_SOURCE_VALUES, name="JobTriggerSource", create_type=False),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )

    # 种子：系统任务（账户清理，默认开启）+ 普通任务示例（默认关闭）
    _seed_job(
        name="每日账户清理",
        task_type="ACCOUNT_CLEANUP",
        kind="SYSTEM",
        enabled=True,
        cron_expr="0 4 * * *",
        description="物理清理已过保留期的软删除账户（系统任务，仅可编辑）。",
    )
    _seed_job(
        name="收盘后行情同步",
        task_type="MARKET_DATA_SYNC",
        kind="NORMAL",
        enabled=False,
        cron_expr="0 16 * * 1-5",
        description="工作日 16:00 遍历全部组合同步实时行情并重建快照/净值。",
    )
    _seed_job(
        name="证券主数据同步",
        task_type="SECURITY_MASTER_SYNC",
        kind="NORMAL",
        enabled=False,
        cron_expr="0 3 * * 1-5",
        description="配置文件驱动同步系统级证券主数据（MASTER_LIST 接口）。",
    )


def _r6e5f4a3b2c1d_down() -> None:
    bind = op.get_bind()
    op.drop_table("job_run_logs")
    op.drop_table("job_configs")
    sa.Enum(*_JOB_TRIGGER_SOURCE_VALUES, name="JobTriggerSource").drop(bind, checkfirst=True)
    sa.Enum(*_JOB_RUN_STATUS_VALUES, name="JobRunStatus").drop(bind, checkfirst=True)
    sa.Enum(*_JOB_KIND_VALUES, name="JobKind").drop(bind, checkfirst=True)
    sa.Enum(*_JOB_TASK_TYPE_VALUES, name="JobTaskType").drop(bind, checkfirst=True)


"""用户个性化行情同步配置表 + 移除全局行情同步任务。

背景：把行情自动同步从「管理员全局普通任务 MARKET_DATA_SYNC」改造为
「每个用户自己的配置（按日/周/月周期，只同步自己的组合）」，仍由 APScheduler
统一调度。故：
- 新增 ``user_quote_sync_configs`` 表（每用户一条，upsert）。
- 删除 ``job_configs`` 中已存在的 ``task_type='MARKET_DATA_SYNC'`` 的全局任务行。
  （JobTaskType 枚举值保留，删除 PG 枚举值成本高且现有数据不依赖，不做。）
"""


# revision identifiers, used by Alembic.


def _s1a2b3c4d5e6f_up() -> None:
    # 每用户行情同步配置
    op.create_table(
        "user_quote_sync_configs",
        sa.Column(
            "user_id",
            sa.String(length=36),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            primary_key=True,
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("frequency", sa.String(length=6), nullable=False, server_default=sa.text("'DAY'")),
        sa.Column("time", sa.String(length=5), nullable=False, server_default=sa.text("'09:00'")),
        sa.Column("weekday", sa.Integer(), nullable=True),
        sa.Column("day_of_month", sa.Integer(), nullable=True),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_status", sa.String(length=10), nullable=True),
        sa.Column("last_message", sa.String(length=512), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )

    # 移除全局行情同步任务（改造后由每用户配置取代）
    op.execute(sa.text("DELETE FROM job_configs WHERE task_type = 'MARKET_DATA_SYNC'"))


def _s1a2b3c4d5e6f_down() -> None:
    op.drop_table("user_quote_sync_configs")


"""将 portfolio_securities.master_id 外键改为 DEFERRABLE INITIALLY DEFERRED。

背景：证券主数据自愈（_normalize_and_dedupe_masters）在重推 code/asset_class 后，
需把 securities.id 从随机 UUID 重派生为 master_id_for(asset_class, code)，并同步迁移
portfolio_securities.master_id 引用。重派生分两步：先把子表引用迁到新 id，再把父表
securities.id 改为新 id。非延迟外键会在「改父表主键时子表仍引用旧 id」这一步立即报
ForeignKeyViolationError。改为延迟到事务提交时检查即可让两步都落库后再统一校验，
彼时子表已指向新 id，约束一致。

仅改外键的可延迟属性，不动列、不动数据、不破坏既有迁移链。
"""


# revision identifiers, used by Alembic.

_FK_NAME = "portfolio_securities_master_id_fkey"


def _t0u1v2w3x4y5_up() -> None:
    op.drop_constraint(_FK_NAME, "portfolio_securities", type_="foreignkey")
    op.create_foreign_key(
        _FK_NAME,
        "portfolio_securities",
        "securities",
        ["master_id"],
        ["id"],
        ondelete="CASCADE",
        deferrable=True,
        initially="DEFERRED",
    )


def _t0u1v2w3x4y5_down() -> None:
    op.drop_constraint(_FK_NAME, "portfolio_securities", type_="foreignkey")
    op.create_foreign_key(
        _FK_NAME,
        "portfolio_securities",
        "securities",
        ["master_id"],
        ["id"],
        ondelete="CASCADE",
    )


"""移除 LOCAL_COMMAND 任务类型（REP-003 · owner 裁决 C 档，精简版）。

背景：``JobTaskType.LOCAL_COMMAND`` 是产品内置的任意命令执行通道
（``app/core/scheduler.py`` 原 ``_local_command`` 用 ``subprocess.run(shell=True)``）。
虽创建 / 触发端点均收口在 ``require_admin``，但属「admin 会话一旦被劫持即一步拿到
容器 shell」的 RCE 原语。经裁决按 **C 档彻底移除**该任务类型（Python 端枚举成员、
处理器、管理端 handler 元数据已同步删除）。

⚠️ **关键事实：PostgreSQL 不支持 ``ALTER TYPE ... DROP VALUE``**

PG 的 ``ALTER TYPE`` 对枚举仅支持 ``ADD VALUE`` 与 ``RENAME VALUE``，**从未提供
DROP VALUE**。本迁移初版曾尝试 ``ALTER TYPE "JobTaskType" DROP VALUE 'LOCAL_COMMAND'``，
在 PG 16.14 实测报 ``syntax error at or near "VALUE"``。删除枚举值只剩两条路：

1. 直接删 ``pg_enum`` 系统表行（hack，非官方支持）；
2. **重建类型**（官方推荐路径）—— 本迁移采用。

重建步骤（顺序不可颠倒）：列降级为 ``text`` → 删旧类型 → 建新类型 → 列改回枚举。
整个 ``upgrade()`` 在同一事务内执行，PG 支持事务性 DDL，故失败可整体回滚。

**数据清理（精简版已移除）**：各环境（dev / test / prod）均确认无 ``LOCAL_COMMAND``
存量任务与日志，故本迁移**不再包含 ``DELETE`` 语句**——仅重建枚举即可完成移除，
不触碰任何业务数据。若某环境实际存在 ``LOCAL_COMMAND`` 存量行，列改回新枚举时
残留值无法 CAST 而失败；此时需先手动清理存量行（见 git 历史中本迁移的初版 ``DELETE`` 实现）。

接在 ``t0u1v2w3x4y5`` 之后（``down_revision='t0u1v2w3x4y5'``），
严禁改动 revision / down_revision 指针，否则断链。
"""



# revision identifiers, used by Alembic.

# 重建后的枚举值（移除 LOCAL_COMMAND，其余保持原有顺序）
_VALUES_AFTER = (
    "'MARKET_DATA_SYNC', 'SECURITY_MASTER_SYNC', 'HTTP_CALLBACK', "
    "'ACCOUNT_CLEANUP', 'LOG_CLEANUP'"
)
# 回滚时的枚举值（含 LOCAL_COMMAND，顺序与重建前一致）
_VALUES_BEFORE = (
    "'MARKET_DATA_SYNC', 'SECURITY_MASTER_SYNC', 'LOCAL_COMMAND', "
    "'HTTP_CALLBACK', 'ACCOUNT_CLEANUP', 'LOG_CLEANUP'"
)


def _rebuild_enum(values: str) -> None:
    """以给定值集合重建 "JobTaskType" 枚举，并把列改回该类型。"""
    op.execute(text("ALTER TABLE job_configs ALTER COLUMN task_type TYPE text"))
    op.execute(text('DROP TYPE "JobTaskType"'))
    op.execute(text(f'CREATE TYPE "JobTaskType" AS ENUM ({values})'))
    op.execute(
        text(
            'ALTER TABLE job_configs ALTER COLUMN task_type TYPE "JobTaskType" '
            'USING task_type::text::"JobTaskType"'
        )
    )


def _t7u8v9w0x1y2_up() -> None:
    # 重建枚举类型（PG 无 DROP VALUE，见模块 docstring）。
    # 各环境均无 LOCAL_COMMAND 存量数据，无需 DELETE。
    _rebuild_enum(_VALUES_AFTER)


def _t7u8v9w0x1y2_down() -> None:
    # 对称重建为初版 6 值枚举（含 LOCAL_COMMAND）。
    _rebuild_enum(_VALUES_BEFORE)


"""任务表新增 max_logs：控制单个任务执行日志的保留条数上限。

背景：job_run_logs 只写不删，长期运行会无限累积。为控制日志规模，在 job_configs
增加可空列 max_logs：
- NULL 或 <=0：不限制（保持既有行为）
- 正整数：每次执行落库后，该任务按开始时间倒序保留最新 max_logs 条，删除更旧的
具体裁剪逻辑在 app/core/scheduler.py 的 _prune_run_logs。
"""


# revision identifiers, used by Alembic.


def _u1v2w3x4y5z6_up() -> None:
    # 漂移态守卫：开发库可能经 create_all 建表 + stamp 打戳，列已存在；
    # IF NOT EXISTS 使迁移幂等（全新库照常加列，漂移库无操作）。
    op.execute(text("ALTER TABLE job_configs ADD COLUMN IF NOT EXISTS max_logs INTEGER"))


def _u1v2w3x4y5z6_down() -> None:
    # 与 upgrade 对称使用 IF EXISTS，容忍「列已不存在」的漂移库，保证降级不中断。
    op.execute(text("ALTER TABLE job_configs DROP COLUMN IF EXISTS max_logs"))


"""新增统一日志表 app_logs（方案 §4.1）。

承接全站运行错误 / 业务操作日志的持久化。仅建单表，无原生枚举（level/scope 用
VARCHAR + 应用层约束），故迁移零类型创建；幂等守卫用 CREATE TABLE IF NOT EXISTS，
可安全重复执行（不会因表已存在而报错）。

接在 u1v2w3x4y5z6 之后（down_revision='u1v2w3x4y5z6'），严禁改动既有迁移文件，否则断链。
"""


# 导入模型确保注册到 Base.metadata（供 autogenerate 比对）


# revision identifiers, used by Alembic.


def _v2w3x4y5z6a7_up() -> None:
    op.execute(
        sa.text(
            """
            CREATE TABLE IF NOT EXISTS app_logs (
                id VARCHAR(36) PRIMARY KEY DEFAULT gen_random_uuid(),
                level VARCHAR(20) NOT NULL DEFAULT 'info',
                scope VARCHAR(20) NOT NULL DEFAULT 'operation',
                module VARCHAR(64) NOT NULL,
                message TEXT NOT NULL,
                trace TEXT,
                detail JSON,
                user_id VARCHAR(36),
                created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
            )
            """
        )
    )


def _v2w3x4y5z6a7_down() -> None:
    op.execute(sa.text("DROP TABLE IF EXISTS app_logs"))


"""新增 LOG_CLEANUP 系统任务（方案 §4.6）。

- 原生枚举 JobTaskType 扩展 'LOG_CLEANUP'（PG12+ 允许事务内 ADD VALUE，参考
  p4f7a8b9c0d1_asset_class_multiselect 写法；枚举类型名带大写须加引号）。
- 种子写入系统 JobConfig（镜像 r6e5f4a3b2c1d 的 ACCOUNT_CLEANUP 播种：
  名称唯一约束兜底幂等，参数填默认按级别策略）。

接在 v2w3x4y5z6a7 之后（down_revision='v2w3x4y5z6a7'），严禁改动既有迁移文件，否则断链。
"""



# revision identifiers, used by Alembic.


def _w3x4y5z6a7b8_up() -> None:
    # 1) 扩展原生枚举：ALTER TYPE ADD VALUE 必须在独立事务（autocommit）中提交，
    #    否则同一连接后续语句引用新枚举值会报
    #    "unsafe use of new value ... must be committed before they can be used"。
    ctx = op.get_context()
    with ctx.autocommit_block():
        op.execute(
            text("ALTER TYPE \"JobTaskType\" ADD VALUE IF NOT EXISTS 'LOG_CLEANUP'")
        )

    # 2) 种子：系统任务（名称唯一约束兜底，勿重复执行）。须在 ADD VALUE 提交后再执行，
    #    否则 PG 认为新枚举值尚未生效（同一事务内不允许引用）。
    op.execute(
        sa.text(
            """
            INSERT INTO job_configs
                (id, name, task_type, kind, enabled, cron_expr, params, description, created_at, updated_at)
            SELECT
                gen_random_uuid(), '日志中心清理',
                CAST('LOG_CLEANUP' AS "JobTaskType"),
                CAST('SYSTEM' AS "JobKind"),
                true, '0 3 * * *',
                '{"retention_days": {"error": 90, "warning": 30, "info": 7}, '
                '"max_rows": {"error": 20000, "warning": 10000, "info": 5000}, '
                '"notifications_retention_days": 30}'::json,
                '按级别分级清理日志中心：app_logs 过期/超量、已读且超期通知、'
                '未配置 max_logs 的任务日志。系统任务仅可编辑不可删。',
                now(), now()
            WHERE NOT EXISTS (SELECT 1 FROM job_configs WHERE name = '日志中心清理')
            """
        )
    )


def _w3x4y5z6a7b8_down() -> None:
    op.execute(sa.text("DELETE FROM job_configs WHERE name = '日志中心清理'"))
    # 枚举值 PG 不可事务内移除，且其他数据可能已引用，故不 DROP VALUE（与既有迁移一致）。


"""新增 users.token_version 支持 JWT 吊销（REP-011）。

- 改密 / 改邮箱 / 恢复账户时，User.token_version 自增；
- get_current_user 校验 token 携带的 tv 与库内一致，不一致即视为失效（需重登）。
- 存量用户默认 0，旧 token 无 tv 声明按 0 处理，不强制存量用户下线。

接在 w3x4y5z6a7b8 之后（down_revision='w3x4y5z6a7b8'），严禁改动既有迁移文件，否则断链。
"""



# revision identifiers, used by Alembic.


def _x4y5z6a7b8c9_up() -> None:
    # 漂移态守卫：IF NOT EXISTS 使迁移幂等（全新库照常加列，漂移库无操作）。
    # 语义对齐原 sa.Column(Integer, nullable=False, server_default=sa.text("0"))；
    # 存量用户行由 DEFAULT 0 填充，不会违反 NOT NULL。
    op.execute(
        text(
            "ALTER TABLE users ADD COLUMN IF NOT EXISTS "
            "token_version INTEGER NOT NULL DEFAULT 0"
        )
    )


def _x4y5z6a7b8c9_down() -> None:
    # 与 upgrade 对称使用 IF EXISTS，容忍「列已不存在」的漂移库，保证降级不中断。
    op.execute(text("ALTER TABLE users DROP COLUMN IF EXISTS token_version"))


def upgrade() -> None:
    _9a787407d654_up()
    _b1c2d3e4f5a6_up()
    _c2d3e4f5a6b7_up()
    _d3e4f5a6b7c8_up()
    _e4f5a6b7c8d9_up()
    _f5a6b7c8d9e0_up()
    _g6b7c8d9e0f1_up()
    _h7c8d9e0f1g2_up()
    _i8d9e0f1g2h3_up()
    _j9e0f1a2b3c4_up()
    _k0f1a2b3c4d5_up()
    _l1a2b3c4d5e6_up()
    _n2c3d4e5f6g7_up()
    _o3d4e5f6a7b8_up()
    _p4f7a8b9c0d1_up()
    _q9a8b7c6d5e4_up()
    _r6e5f4a3b2c1d_up()
    _s1a2b3c4d5e6f_up()
    _t0u1v2w3x4y5_up()
    _t7u8v9w0x1y2_up()
    _u1v2w3x4y5z6_up()
    _v2w3x4y5z6a7_up()
    _w3x4y5z6a7b8_up()
    _x4y5z6a7b8c9_up()


def downgrade() -> None:
    _x4y5z6a7b8c9_down()
    _w3x4y5z6a7b8_down()
    _v2w3x4y5z6a7_down()
    _u1v2w3x4y5z6_down()
    _t7u8v9w0x1y2_down()
    _t0u1v2w3x4y5_down()
    _s1a2b3c4d5e6f_down()
    _r6e5f4a3b2c1d_down()
    _q9a8b7c6d5e4_down()
    _p4f7a8b9c0d1_down()
    _o3d4e5f6a7b8_down()
    _n2c3d4e5f6g7_down()
    _l1a2b3c4d5e6_down()
    _k0f1a2b3c4d5_down()
    _j9e0f1a2b3c4_down()
    _i8d9e0f1g2h3_down()
    _h7c8d9e0f1g2_down()
    _g6b7c8d9e0f1_down()
    _f5a6b7c8d9e0_down()
    _e4f5a6b7c8d9_down()
    _d3e4f5a6b7c8_down()
    _c2d3e4f5a6b7_down()
    _b1c2d3e4f5a6_down()
    _9a787407d654_down()
