"""initial schema (Phase 1: 12 models + 6 enums)

Revision ID: 9a787407d654
Revises: 
Create Date: 2026-08-08 11:07:12.541162
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a787407d654'
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('avatar', sa.String(length=512), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('bio', sa.String(length=200), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('portfolios',
    sa.Column('id', sa.String(length=36), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_date', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_portfolios_user_id', 'portfolios', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.String(length=36), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('default_portfolio_id', sa.String(length=36), nullable=True),
    sa.Column('default_granularity', sa.String(length=20), nullable=False),
    sa.Column('default_date_range', sa.String(length=20), nullable=False),
    sa.Column('aggregation', sa.String(length=20), nullable=False),
    sa.Column('week_starts_on', sa.Integer(), nullable=False),
    sa.Column('nav_decimals', sa.Integer(), nullable=False),
    sa.Column('xirr_decimals', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(length=20), nullable=False),
    sa.Column('stale_days', sa.Integer(), nullable=False),
    sa.Column('show_liquidated', sa.Boolean(), nullable=False),
    sa.Column('cost_basis_view', sa.String(length=20), nullable=False),
    sa.Column('cash_hint_on_cashflow', sa.Boolean(), nullable=False),
    sa.Column('cash_hint_on_trade', sa.Boolean(), nullable=False),
    sa.Column('amount_thousands', sa.Boolean(), nullable=False),
    sa.Column('amount_abbrev', sa.Boolean(), nullable=False),
    sa.Column('dashboard_layout', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_preferences_user_id')
    )
    op.create_table('asset_snapshots',
    sa.Column('id', sa.String(length=36), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_asset', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('market_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cash_balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('source', sa.Enum('DERIVED', 'MANUAL', name='SnapshotSource'), nullable=False),
    sa.Column('valuation_flag', sa.Enum('EXACT', 'CARRIED_FORWARD', 'COST_BASED', 'MANUAL_INPUT', name='SnapshotValuation'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'date', name='uq_asset_snapshots_portfolio_date')
    )
    op.create_index('ix_asset_snapshots_portfolio_date', 'asset_snapshots', ['portfolio_id', 'date'], unique=False)
    op.create_table('cash_balances',
    sa.Column('id', sa.String(length=36), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cash_balances_portfolio_asof', 'cash_balances', ['portfolio_id', 'as_of'], unique=False)
    op.create_table('cashflows',
    sa.Column('id', sa.String(length=36), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.Enum('BUY', 'SELL', name='CashFlowType'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cashflows_portfolio_date', 'cashflows', ['portfolio_id', 'date'], unique=False)
    op.create_table('daily_nav',
    sa.Column('id', sa.String(length=36), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('unit_nav', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('cumulative_nav', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('year_nav', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('shares', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('base_cumulative_nav', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'date', name='uq_daily_nav_portfolio_date')
    )
    op.create_index('ix_daily_nav_portfolio_date', 'daily_nav', ['portfolio_id', 'date'], unique=False)
    op.create_table('daily_xirr',
    sa.Column('id', sa.String(length=36), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('xirr_value', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'date', name='uq_daily_xirr_portfolio_date')
    )
    op.create_index('ix_daily_xirr_portfolio_date', 'daily_xirr', ['portfolio_id', 'date'], unique=False)
    op.create_table('securities',
    sa.Column('id', sa.String(length=36), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('STOCK', 'FUND', 'BOND', 'OTHER', 'CASH', name='SecurityType'), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'code', name='uq_securities_portfolio_code')
    )
    op.create_table('dividend_records',
    sa.Column('id', sa.String(length=36), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('security_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('type', sa.Enum('CASH', 'STOCK_DIVIDEND', name='DividendType'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dividend_records_portfolio_date', 'dividend_records', ['portfolio_id', 'date'], unique=False)
    op.create_index('ix_dividend_records_security_date', 'dividend_records', ['security_id', 'date'], unique=False)
    op.create_table('security_prices',
    sa.Column('id', sa.String(length=36), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('security_id', sa.String(length=36), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_security_prices_portfolio_security_asof', 'security_prices', ['portfolio_id', 'security_id', 'as_of'], unique=False)
    op.create_table('security_trades',
    sa.Column('id', sa.String(length=36), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('security_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('side', sa.Enum('BUY_SEC', 'SELL_SEC', name='SecuritySide'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('fee_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('commission', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('stamp_tax', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('other', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_security_trades_portfolio_date', 'security_trades', ['portfolio_id', 'date'], unique=False)
    op.create_index('ix_security_trades_security_date', 'security_trades', ['security_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_security_trades_security_date', table_name='security_trades')
    op.drop_index('ix_security_trades_portfolio_date', table_name='security_trades')
    op.drop_table('security_trades')
    op.drop_index('ix_security_prices_portfolio_security_asof', table_name='security_prices')
    op.drop_table('security_prices')
    op.drop_index('ix_dividend_records_security_date', table_name='dividend_records')
    op.drop_index('ix_dividend_records_portfolio_date', table_name='dividend_records')
    op.drop_table('dividend_records')
    op.drop_table('securities')
    op.drop_index('ix_daily_xirr_portfolio_date', table_name='daily_xirr')
    op.drop_table('daily_xirr')
    op.drop_index('ix_daily_nav_portfolio_date', table_name='daily_nav')
    op.drop_table('daily_nav')
    op.drop_index('ix_cashflows_portfolio_date', table_name='cashflows')
    op.drop_table('cashflows')
    op.drop_index('ix_cash_balances_portfolio_asof', table_name='cash_balances')
    op.drop_table('cash_balances')
    op.drop_index('ix_asset_snapshots_portfolio_date', table_name='asset_snapshots')
    op.drop_table('asset_snapshots')
    op.drop_table('user_preferences')
    op.drop_index('ix_portfolios_user_id', table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_table('users')
    # ### end Alembic commands ###
